export { default as Home } from "./home";
export { default as School } from "./school";
export { default as Club } from "./../club/Club";
export { default as Community } from "../community";
export { default as Write } from "./../club/Write";
export { default as Login } from "./user/login";
export { default as Join } from "./user/join";
export { default as Modify } from "./user/modify";
export { default as Article } from "./../club/Article";
