export default {
  menuList: [
    { name: "Info", link: "School" },
    { name: "SW", link: "Club/SW" },
    { name: "Food", link: "Club/Food" },
    { name: "Finance", link: "Club/Commerce" },
    { name: "Community", link: "Community" },
  ],
  clubs: {
    SW: [
      { name: "웹프론트반", link: "webfront" },
      { name: "너튜브크리에이터반", link: "youtubecreator" },
      { name: "마인드스톰EV3코딩반", link: "ev3" },
      { name: "슈즈디자인반", link: "shoes" },
      { name: "젤예쁜손", link: "jell" },
      { name: "수공예반", link: "handicraft" },
      { name: "디자인기초반", link: "basicdesign" },
      { name: "쥬얼리반", link: "jewellery" },
      { name: "실무디자인반", link: "practicaldesign" },
    ],
    Food: [
      { name: "조리미디어연구반", link: "cookmedia" },
      { name: "골목식당반", link: "streetfood" },
    ],
    Commerce: [
      { name: "경제탐구반", link: "exploereconomy" },
      { name: "회계실무반", link: "practicalcommerce" },
      { name: "금융마을 탐방반", link: "financetown" },
      { name: "언더라이팅반", link: "underlighting" },
    ],
    Other: [
      { name: "응원반", link: "cheer" },
      { name: "댄스반", link: "dance" },
      { name: "방송반", link: "broadcase" },
      { name: "홍보하늘반", link: "promotion1" },
      { name: "홍보바람반", link: "promotion2" },
      { name: "홍보별반", link: "promotion3" },
      { name: "재능기부반", link: "talent" },
      { name: "또바기반", link: "ddobagi" },
      { name: "홍보영상제작반", link: "promotionvideo" },
      { name: "퍼즐맞추기반", link: "puzzle" },
      { name: "보드게임반", link: "boardgame" },
      { name: "프라모델반", link: "plamodel" },
      { name: "한양답사반", link: "hanyang" },
      { name: "당구반", link: "billiards" },
      { name: "설탕공예반", link: "sugar" },
      { name: "달보드레반", link: "dalbodre" },
      { name: "밴드반", link: "band" },
      { name: "스크린셀러반", link: "screenseller" },
      { name: "중구문화체험반", link: "jungguculture" },
      { name: "포트폴리오반", link: "portfolio" },
    ],
  },
};
